server:
  port: 8763
spring:
  application:
    name: service-message
  #zipkin:
    #base-url: http://localhost:9411



  cloud:
    config:
      uri: http://localhost:1201/
      profile: dev
      label: master

